version: '3.8'
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: url_shortner_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: url_shortner
      MYSQL_USER: url_user
      MYSQL_PASSWORD: root123
    volumes:
      - "./src/database/config/init.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always

volumes:
  mysql_data:
    driver: local
